export type Role = 'user' | 'admin'
export type User = { id:string; username:string; role:Role; disabled:boolean; email?:string; avatar_url?:string; linuxdo_id?:number; linuxdo_username?:string; trust_level?:number; max_output_tokens?:number; created_at:string; last_active_at:string; repositories?:number; storage_bytes?:number; search_p95_ms?:number; retrieval_today?:number; enhance_today?:number; upload_today?:number }
export type AuthConfig = { registration_enabled:boolean; turnstile_site_key:string; linuxdo_enabled:boolean; email_domains?:string[]; version?:string }
export type QuotaSettings = { storage_limit_mb:number; daily_retrieval:number; daily_enhance:number; daily_upload:number; rpm_retrieval:number; rpm_upload:number; rpm_enhance:number }
export type QuotaStatus = { limits:QuotaSettings; unlimited:boolean; usage:{ storage_bytes:number; retrieval:number; enhance:number; upload:number } }
export type Repository = { id:string; owner_id:string; owner_username?:string; name:string; root_path:string; branch:string; base_snapshot:string; snapshot_id?:string; status:string; file_count:number; chunk_count:number; storage_bytes:number; current_revision:number; indexed_revision:number; index_lag_ms:number; search_p95_ms:number; embedding_model:string; last_synced_at:string; updated_at:string; paused:boolean }
export type Overview = { repositories:number; files:number; chunks:number; embedded_chunks:number; storage_bytes:number; healthy:number; lagging:number; failed_jobs:number; active_users:number; search_p50_ms:number; search_p95_ms:number; search_p99_ms:number; latency_points:MetricPoint[] }
export type MetricPoint = { scope:string; repository_id?:string; name:string; value:number; timestamp:string }
export type SearchHit = { path:string; start_line:number; end_line:number; symbol?:string; content:string; score:number; lexical_score:number; path_score:number; symbol_score:number; semantic_score:number; rerank_score?:number }
export type SearchResponse = { formatted_retrieval:string; hits:SearchHit[]; duration_ms:number; candidate_count:number; token_estimate:number; degraded:boolean }
export type EvalCase = { id:string; repository_id:string; query:string; expected_paths:string[]; expected_keywords:string[]; created_at:string }
export type EvalCaseResult = { case:EvalCase; path_hit:boolean; matched_paths:string[]; keyword_recall:number; duration_ms:number; degraded:boolean }
export type EvalRun = { results:EvalCaseResult[]; summary:{ cases:number; path_cases:number; keyword_cases:number; path_recall?:number; keyword_recall?:number; avg_latency_ms?:number } }
export type AceUsage = { user_id:string; username:string; endpoint:string; calls:number; units:number; last_day:string }
export type AceUsageDay = { day:string; endpoint:string; calls:number; units:number }
export type AceProject = { name:string; owner_id?:string; owner_username?:string; snapshot_id:string; file_count:number; chunk_count:number; embedded_count:number; storage_bytes:number; updated_at:string }
export type AuditEvent = { id:string; actor:string; action:string; target_type:string; target_id:string; result:string; metadata?:Record<string,unknown>; created_at:string }
export type SystemSettings = { registration_enabled:boolean; smtp_configured:boolean }
export type Announcement = { id:string; title:string; content:string; author:string; created_at:string }
export type RetrievalSettings = { embedding_provider:string; embedding_url:string; embedding_model:string; embedding_dimensions:number; reranker_enabled:boolean; reranker_model:string; reranker_top_k:number; enhancer_provider:string; enhancer_url:string; enhancer_model:string; summary_model:string; summary_budget:number; embedding_api_key:string; enhancer_api_key:string; updated_at:string }
export type AnalyticsHour = { hour:string; searches:number; avg_ms?:number; p50_ms?:number; p95_ms?:number; degraded?:number; degraded_rate:number; requests:number; ingest_bytes:number; ingest_blobs:number; cache_hits:number; cache_misses:number; cache_rate:number; inline_count?:number; inline_avg_ms?:number; inline_max_ms?:number }
export type Analytics = { generated_at:string; hours:AnalyticsHour[]; total_searches:number; total_degraded:number; total_requests:number; total_ingest_mb:number; cache_hit_rate:number }
